project_id = "buexhnmwraxzbtjymzwf"

[functions.siteverify]
verify_jwt = false

[functions.sdk]
verify_jwt = false

[functions.moderate-review]
verify_jwt = false

[functions.generate-captcha]
verify_jwt = false
